version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  identifier:
    # image: semtech/mu-identifier:latest
    ports:
      - 80:80
  database:
    image: semtech/mu-authorization:0.6.0-beta.2
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
  mocklogin:
    image: kanselarij/mock-login-service:1.0.0
    volumes:
      - ./config/mocklogin:/config
    logging: *default-logging
