version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  database:
    image: semtech/mu-authorization:0.6.0-beta.2
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./config/search:/search
    ports:
      - 127.0.0.1:5601:5601
    userns_mode: "host"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    restart: "no"
  elasticsearch:
    ports:
      - 127.0.0.1:9200:9200
  login:
    entrypoint: "echo 'service disabled'"
    restart: "no"
  mocklogin:
    image: kanselarij/mock-login-service:1.0.0
    volumes:
      - ./config/mocklogin:/config
    logging: *default-logging
