x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    restart: "no"
  identifier:
    ports:
      - 80:80
    restart: "no"
  dispatcher:
    restart: "no"
  migrations:
    volumes:
      - ./config/dev-migrations:/data/migrations/dev/
    restart: "no"
  database:
    restart: "no"
  triplestore:
    ports:
      - 8890:8890
    restart: "no"
  delta-notifier:
    restart: "no"
  login:
    entrypoint: echo "Service disabled"
    restart: "no"
  mock-login:
    image: kanselarij/mock-login-service:2.4.0
    logging: *default-logging
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
  range-file:
    restart: "no"
  search:
    restart: "no"
    environment:
      JRUBY_OPTIONS: "-J-Xmx2g"
      NUMBER_OF_THREADS: "2"
  elasticsearch:
    restart: "no"
  tika:
    restart: "no"
  distribution:
    environment:
      LOG_SPARQL_ALL: "true"
      DEBUG_AUTH_HEADERS: "true"
    restart: "no"
  sink:
    restart: "no"
  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.3
    depends_on:
      - elasticsearch
    ports:
      - 127.0.0.1:5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    logging: *default-logging
    restart: "no"
