version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  database:
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      INSPECT_OUTGOING_SPARQL_QUERIES: "true"
      LOG_INCOMING_SPARQL_QUERIES: "true"
      INSPECT_INCOMING_SPARQL_QUERIES: "true"
      LOG_ACCESS_RIGHTS: "true"
      INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      LOG_DELTA_MESSAGES: "true"
      LOG_DELTA_CLIENT_COMMUNICATION: "true"
      LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./config/search:/search
    ports:
      - 127.0.0.1:5601:5601
    userns_mode: "host"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    restart: "no"
  elasticsearch:
    ports:
      - 127.0.0.1:9200:9200
  mocklogin:
    image: kanselarij/mock-login-service:1.0.0
    volumes:
      - ./config/mocklogin:/config
    logging: *default-logging
  distribution:
    environment:
      LOG_SPARQL_ALL: "true"
      DEBUG_AUTH_HEADERS: "true"
