PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX code: <http://kanselarij.vo.data.gift/id/concept/toegangs-niveaus/>

DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        code:d335f7e3-aefd-4f93-81a2-1629c2edafa3 skos:prefLabel "Intern Regering"@nl .
        code:abe4c18d-13a9-45f0-8cdd-c493eabbbe29 skos:prefLabel "Intern Overheid"@nl .
        code:e3d64f24-4feb-4770-8212-e9e3e23a7d29 skos:prefLabel "Parlement"@nl .
    }
}

;

INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        code:d335f7e3-aefd-4f93-81a2-1629c2edafa3 skos:prefLabel "Minister"@nl .
        code:abe4c18d-13a9-45f0-8cdd-c493eabbbe29 skos:prefLabel "Kabinet & Advies"@nl .
        code:e3d64f24-4feb-4770-8212-e9e3e23a7d29 skos:prefLabel "Intern Overheid"@nl .
    }
}
