(define-resource document ()
  :class (s-prefix "foaf:Document")
  :properties `((:name                  :string   ,(s-prefix "dct:title"))
                (:created               :datetime ,(s-prefix "dct:created")))
  :has-many `((document-version         :via ,(s-prefix "besluitvorming:heeftVersie")
                                        :as "document-versions"))
  :has-one `((document-type             :via ,(s-prefix "ext:documentType")
                                        :as "type"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/documenten/")
  :features '(include-uri)
  :on-path "documents")

(define-resource document-version ()
  :class (s-prefix "ext:DocumentVersie")
  :properties `((:version-number        :string   ,(s-prefix "ext:versieNummer"))
                (:created               :datetime ,(s-prefix "dct:created"))
                (:confidential          :boolean  ,(s-prefix "ext:vertrouwelijk")))
  :has-one `((file                      :via      ,(s-prefix "ext:file")
                                        :as "file")
            (document                   :via      ,(s-prefix "besluitvorming:heeftVersie")
                                        :inverse t
                                        :as "document")
            (access-level               :via ,(s-prefix "ext:toegangsniveauVoorDocumentVersie")
                                        :as "access-level"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/document-versies/")
  :features `(include-uri)
  :on-path "document-versions")

(define-resource document-type ()
  :class (s-prefix "ext:DocumentTypeCode")
  :properties `((:label             :string ,(s-prefix "skos:prefLabel"))
                (:scope-note        :string ,(s-prefix "skos:scopeNote"))
                (:priority          :number ,(s-prefix "ext:prioriteit"))
                (:alt-label         :string ,(s-prefix "skos:altLabel")))
  :has-many `((document             :via    ,(s-prefix "ext:documentType")
                                    :inverse t
                                    :as "documents")
              (document-type        :via    ,(s-prefix "skos:broader")
                                    :inverse t
                                    :as "subtypes"))
  :has-one `((document-type         :via    ,(s-prefix "skos:broader")
                                    :as "supertype"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/concept/document-type-codes/")
  :features '(include-uri no-pagination-defaults)
  :on-path "document-types")

(define-resource access-level ()
  :class (s-prefix "ext:ToegangsniveauCode") ;; NOTE: as well as skos:Concept
  :properties `((:label       :string ,(s-prefix "skos:prefLabel"))
                (:scope-note  :string ,(s-prefix "skos:scopeNote"))
                (:alt-label   :string ,(s-prefix "skos:altLabel"))
                (:priority    :number ,(s-prefix "ext:priority")))
  :has-many `((document-version    :via ,(s-prefix "ext:toegangsniveauVoorDocumentVersie")
                                   :inverse t
                                  :as "document-versions"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/concept/toegangsniveaus/")
  :features '(include-uri no-pagination-defaults)
  :on-path "access-levels")
