(define-resource meeting ()
  :class (s-prefix "oc:Meeting")
  :properties `((:started-at                :datetime ,(s-prefix "prov:startedAtTime"))
                (:extra-info                :string   ,(s-prefix "ext:extraInfo")))
  :has-many `((agendaitem               :via      ,(s-prefix "oc:agendaItem")
                                        :as "agenda-items")
              (document                 :via      ,(s-prefix "oc:documents")
                                        :as "documents"))
                                        
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/oc-zittingen/")
  :features '(include-uri)
  :on-path "meetings")

(define-resource agendaitem ()
  :class (s-prefix "oc:AgendaItem")
  :properties `((:priority            :number   ,(s-prefix "oc:priority"))
                (:sub-priority        :string   ,(s-prefix "oc:subPriority"))
                (:subject             :string   ,(s-prefix "dct:subject"))
                ; (:distribution-date   :date     ,(s-prefix "oc:distributionDate"))
               )
  :has-one `((case                    :via      ,(s-prefix "oc:caseAgendaItem")
                                      :inverse t
                                      :as "case")
             (meeting                 :via      ,(s-prefix "oc:agendaItem")
                                      :inverse t
                                      :as "meeting")
             (document                :via     ,(s-prefix "oc:notification")
                                      :as "notification"))
  :has-many `((government-body        :via      ,(s-prefix "oc:submitter")
                                      :as "submitters")
              (document               :via     ,(s-prefix "oc:documents")
                                      :as "documents")
              (document-version       :via     ,(s-prefix "oc:notificationRelatedDocuments")
                                      :as "notification-related-documents"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/oc-agendapunten/")
  :features `(include-uri)
  :on-path "agendaitems")

(define-resource case ()
  :class (s-prefix "oc:Case")
  :properties `((:identifier          :string   ,(s-prefix "dct:identifier")))
  :has-many `((agendaitem             :via      ,(s-prefix "oc:caseAgendaItem")
                                      :as "agenda-items"))
  :resource-base (s-url "http://kanselarij.vo.data.gift/id/oc-dossiers/")
  :features `(include-uri)
  :on-path "cases")
